# Site settings
title: kNdlogs
email: knd.rio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Logs, exponentials, graphs, results, resumes, samples, reviews, mails, posts, comments, functions, snippets, scripts, poems AND anything else github can hold OR the links go outside or die; Not just another WordPress blog or site; @Author Kennedy Carvalho;
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kndrio.github.io" # the base hostname & protocol for your site
twitter_username: kndrio
github_username:  kndrio

# Build settings
markdown: kramdown
